// Package demo fills the app with a believable DACH construction market and
// with example profiles a visitor can step into.
//
// Why this exists: an empty marketplace explains nothing. Someone opening
// mm.m-2.cc for the first time should be able to type one sentence and get a
// real ranked answer, and should be able to look at the product from a
// Generalunternehmer's and a Subunternehmer's side without registering.
package demo

import (
	"time"

	"mm-machine/internal/model"
)

func day(year int, month time.Month, d int) time.Time {
	return time.Date(year, month, d, 8, 0, 0, 0, time.UTC)
}

// Offers is the demand side of the demo market.
func Offers() []model.Offer {
	now := time.Now()
	return []model.Offer{
		{ID: "MM-2101", Title: "Photovoltaik-Dachmontage Gewerbehalle", Location: "München, DE", Category: "Energietechnik", Amount: "420 Module", Budget: "EUR 146k", Status: "process", Signal: "Attention", Supplier: "Voltwerk GmbH", Progress: 68, Attention: "Drei Anfragen brauchen eine Prüfung der Dokumenten-Laufzeit", Trade: "energy", Region: "München, DE", CrewSize: 8, Start: day(2026, time.October, 5), Requirements: []string{"a1", "insurance"}, Languages: []string{"de", "en"}, CreatedAt: now.Add(-72 * time.Hour), UpdatedAt: now.Add(-12 * time.Minute)},
		{ID: "MM-2102", Title: "Ladenbau Umbau Innenstadt", Location: "Zürich, CH", Category: "Innenausbau", Amount: "1.800 m²", Budget: "EUR 82k", Status: "requested", Signal: "OK", Supplier: "Alpine Montage", Progress: 36, Attention: "Fünf Rückmeldungen von Nachunternehmern liegen vor", Trade: "interior", Region: "Zürich, CH", CrewSize: 6, Start: day(2026, time.September, 21), Requirements: []string{"a1"}, Languages: []string{"de"}, CreatedAt: now.Add(-96 * time.Hour), UpdatedAt: now.Add(-38 * time.Minute)},
		{ID: "MM-2103", Title: "Stahlbau Lagerhalle", Location: "Rotterdam, NL", Category: "Stahlbau", Amount: "96 t", Budget: "EUR 310k", Status: "open", Signal: "OK", Supplier: "Nordline Build", Progress: 22, Attention: "Materialliste bestätigt, Kolonne gesucht", Trade: "steel", Region: "Rotterdam, NL", CrewSize: 12, Start: day(2026, time.November, 2), Requirements: []string{"a1", "insurance", "certificates"}, Languages: []string{"nl", "en"}, CreatedAt: now.Add(-120 * time.Hour), UpdatedAt: now.Add(-time.Hour)},
		{ID: "MM-2104", Title: "Hotelbäder Sanierung", Location: "Wien, AT", Category: "Sanitär", Amount: "74 Zimmer", Budget: "EUR 228k", Status: "done", Signal: "Review", Supplier: "Prime Install", Progress: 100, Attention: "Abnahmefenster offen, Bewertung ausstehend", Trade: "sanitary", Region: "Wien, AT", CrewSize: 5, Start: day(2026, time.June, 3), Requirements: []string{"a1"}, Languages: []string{"de"}, CreatedAt: now.Add(-400 * time.Hour), UpdatedAt: now.Add(-26 * time.Hour)},
		{ID: "MM-2105", Title: "Elektroinstallation Neubau Bürogebäude", Location: "München, DE", Category: "Elektro", Amount: "9 Etagen", Budget: "EUR 410k", Status: "open", Signal: "OK", Supplier: "Stadtwerk Bau", Progress: 8, Attention: "Kolonne mit mindestens sechs Elektrikern gesucht", Trade: "electrical", Region: "München, DE", CrewSize: 6, Start: day(2026, time.October, 12), Requirements: []string{"a1", "insurance"}, Languages: []string{"de"}, CreatedAt: now.Add(-40 * time.Hour), UpdatedAt: now.Add(-3 * time.Hour)},
		{ID: "MM-2106", Title: "Trockenbau Klinik-Erweiterung", Location: "Stuttgart, DE", Category: "Trockenbau", Amount: "4.200 m²", Budget: "EUR 190k", Status: "requested", Signal: "Attention", Supplier: "Südbau GmbH", Progress: 30, Attention: "Nachweis Brandschutzqualifikation fehlt bei zwei Bietern", Trade: "drywall", Region: "Stuttgart, DE", CrewSize: 10, Start: day(2026, time.September, 28), Requirements: []string{"a1", "certificates"}, Languages: []string{"de", "pl"}, CreatedAt: now.Add(-60 * time.Hour), UpdatedAt: now.Add(-5 * time.Hour)},
		{ID: "MM-2107", Title: "Lüftungsanlagen Rechenzentrum", Location: "Frankfurt, DE", Category: "Heizung/Klima", Amount: "12 Anlagen", Budget: "EUR 520k", Status: "open", Signal: "OK", Supplier: "Rhein Klima", Progress: 5, Attention: "Zutrittsprüfung für Rechenzentrum notwendig", Trade: "hvac", Region: "Frankfurt, DE", CrewSize: 9, Start: day(2026, time.November, 16), Requirements: []string{"a1", "insurance", "certificates"}, Languages: []string{"de", "en"}, CreatedAt: now.Add(-30 * time.Hour), UpdatedAt: now.Add(-90 * time.Minute)},
		{ID: "MM-2108", Title: "Sanitärinstallation Wohnanlage", Location: "Berlin, DE", Category: "Sanitär", Amount: "120 Wohnungen", Budget: "EUR 340k", Status: "process", Signal: "OK", Supplier: "Nordbau Berlin", Progress: 55, Attention: "Zweite Kolonne für Bauabschnitt B gesucht", Trade: "sanitary", Region: "Berlin, DE", CrewSize: 8, Start: day(2026, time.August, 18), Requirements: []string{"a1"}, Languages: []string{"de", "pl"}, CreatedAt: now.Add(-200 * time.Hour), UpdatedAt: now.Add(-7 * time.Hour)},
		{ID: "MM-2109", Title: "Stahltreppen Montage Parkhaus", Location: "Linz, AT", Category: "Stahlbau", Amount: "34 Läufe", Budget: "EUR 95k", Status: "open", Signal: "OK", Supplier: "Donau Stahl", Progress: 12, Attention: "Kranstellung durch Auftraggeber", Trade: "steel", Region: "Linz, AT", CrewSize: 4, Start: day(2026, time.October, 20), Requirements: []string{"a1", "insurance"}, Languages: []string{"de"}, CreatedAt: now.Add(-52 * time.Hour), UpdatedAt: now.Add(-4 * time.Hour)},
		{ID: "MM-2110", Title: "Innenausbau Flagship Store", Location: "Hamburg, DE", Category: "Innenausbau", Amount: "900 m²", Budget: "EUR 210k", Status: "requested", Signal: "OK", Supplier: "Elbwerk Interior", Progress: 42, Attention: "Termin steht, Kolonne muss Nachtarbeit leisten können", Trade: "interior", Region: "Hamburg, DE", CrewSize: 7, Start: day(2026, time.September, 14), Requirements: []string{"a1", "insurance"}, Languages: []string{"de", "en"}, CreatedAt: now.Add(-88 * time.Hour), UpdatedAt: now.Add(-9 * time.Hour)},

		// The following widen the market past the first ten offers: more
		// regions (AT/CH/NL beyond the capitals), and the awkward cases that
		// make search worth trying — an offer nobody can staff, two
		// near-identical offers in one city, and work in a region no seeded
		// crew covers (see the Attention text on MM-2112 and MM-2120).
		{ID: "MM-2111", Title: "Solarpark Freiflächenanlage", Location: "Leipzig, DE", Category: "Energietechnik", Amount: "38.000 Module", Budget: "EUR 1.2M", Status: "open", Signal: "OK", Supplier: "Leipziger Energiewerke", Progress: 4, Attention: "Ausschreibung läuft, Kolonne für Montage und Verkabelung gesucht", Trade: "energy", Region: "Leipzig, DE", CrewSize: 16, Start: day(2026, time.December, 1), Requirements: []string{"a1", "insurance", "certificates"}, Languages: []string{"de", "en"}, CreatedAt: now.Add(-20 * time.Hour), UpdatedAt: now.Add(-6 * time.Hour)},
		{ID: "MM-2112", Title: "Lüftungssanierung Bürogebäude", Location: "Bremen, DE", Category: "Heizung/Klima", Amount: "6 Anlagen", Budget: "EUR 68k", Status: "open", Signal: "Attention", Supplier: "Weser Facility", Progress: 0, Attention: "Keine Klima-Kolonne in der Region gemeldet, Umkreissuche nötig", Trade: "hvac", Region: "Bremen, DE", CrewSize: 5, Start: day(2026, time.October, 27), Requirements: []string{"a1", "insurance"}, Languages: []string{"de"}, CreatedAt: now.Add(-14 * time.Hour), UpdatedAt: now.Add(-2 * time.Hour)},
		{ID: "MM-2113", Title: "Trockenbau Bürogebäude Altona", Location: "Hamburg, DE", Category: "Trockenbau", Amount: "2.100 m²", Budget: "EUR 96k", Status: "open", Signal: "OK", Supplier: "Elbwerk Interior", Progress: 10, Attention: "Grundriss final, Kolonne für Dezember gesucht", Trade: "drywall", Region: "Hamburg, DE", CrewSize: 9, Start: day(2026, time.December, 7), Requirements: []string{"a1"}, Languages: []string{"de", "en"}, CreatedAt: now.Add(-18 * time.Hour), UpdatedAt: now.Add(-90 * time.Minute)},
		{ID: "MM-2114", Title: "Trockenbau Bürogebäude Altona Nord", Location: "Hamburg, DE", Category: "Trockenbau", Amount: "2.300 m²", Budget: "EUR 101k", Status: "open", Signal: "OK", Supplier: "Nordbau Berlin", Progress: 6, Attention: "Zweites Baufeld desselben Projekts, eigene Ausschreibung", Trade: "drywall", Region: "Hamburg, DE", CrewSize: 9, Start: day(2026, time.December, 14), Requirements: []string{"a1"}, Languages: []string{"de", "en"}, CreatedAt: now.Add(-16 * time.Hour), UpdatedAt: now.Add(-70 * time.Minute)},
		{ID: "MM-2115", Title: "Stahlkonstruktion Messehalle", Location: "Basel, CH", Category: "Stahlbau", Amount: "58 t", Budget: "EUR 240k", Status: "requested", Signal: "OK", Supplier: "Rhybau AG", Progress: 24, Attention: "Statik freigegeben, drei Angebote liegen vor", Trade: "steel", Region: "Basel, CH", CrewSize: 10, Start: day(2026, time.October, 19), Requirements: []string{"a1", "insurance", "certificates"}, Languages: []string{"de", "fr"}, CreatedAt: now.Add(-44 * time.Hour), UpdatedAt: now.Add(-5 * time.Hour)},
		{ID: "MM-2116", Title: "Bäder Sanierung Wohnanlage", Location: "Graz, AT", Category: "Sanitär", Amount: "58 Wohnungen", Budget: "EUR 165k", Status: "open", Signal: "OK", Supplier: "Steirisch Wohnbau", Progress: 2, Attention: "Bewohnte Anlage, Etappenplan gefordert", Trade: "sanitary", Region: "Graz, AT", CrewSize: 4, Start: day(2026, time.November, 9), Requirements: []string{"a1"}, Languages: []string{"de"}, CreatedAt: now.Add(-10 * time.Hour), UpdatedAt: now.Add(-3 * time.Hour)},
		{ID: "MM-2117", Title: "Ladenbau Flagshipstore", Location: "Amsterdam, NL", Category: "Innenausbau", Amount: "1.200 m²", Budget: "EUR 175k", Status: "requested", Signal: "OK", Supplier: "Damrak Retail", Progress: 18, Attention: "Eröffnungstermin fix, keine Verschiebung möglich", Trade: "interior", Region: "Amsterdam, NL", CrewSize: 8, Start: day(2026, time.September, 30), Requirements: []string{"a1", "insurance"}, Languages: []string{"nl", "en"}, CreatedAt: now.Add(-70 * time.Hour), UpdatedAt: now.Add(-4 * time.Hour)},
		{ID: "MM-2118", Title: "Elektroinstallation Logistikzentrum", Location: "Utrecht, NL", Category: "Elektro", Amount: "22.000 m²", Budget: "EUR 380k", Status: "open", Signal: "OK", Supplier: "Nordline Build", Progress: 0, Attention: "Ausschreibung neu eröffnet", Trade: "electrical", Region: "Utrecht, NL", CrewSize: 11, Start: day(2027, time.January, 12), Requirements: []string{"a1", "insurance", "certificates"}, Languages: []string{"nl", "en"}, CreatedAt: now.Add(-8 * time.Hour), UpdatedAt: now.Add(-time.Hour)},
		{ID: "MM-2119", Title: "Wärmepumpen Umrüstung Hotel", Location: "Salzburg, AT", Category: "Energietechnik", Amount: "3 Gebäude", Budget: "EUR 112k", Status: "process", Signal: "OK", Supplier: "Alpin Energie", Progress: 45, Attention: "Erstes Gebäude fertig, zwei folgen", Trade: "energy", Region: "Salzburg, AT", CrewSize: 5, Start: day(2026, time.September, 1), Requirements: []string{"a1", "certificates"}, Languages: []string{"de"}, CreatedAt: now.Add(-260 * time.Hour), UpdatedAt: now.Add(-11 * time.Hour)},
		{ID: "MM-2120", Title: "Hallenneubau Distributionszentrum", Location: "Dortmund, DE", Category: "Stahlbau", Amount: "210 t", Budget: "EUR 1.8M", Status: "open", Signal: "Attention", Supplier: "Ruhr Logistikbau", Progress: 0, Attention: "Verlangt eine Kolonne mit 20 Personen, keine im Netzwerk verfügbar", Trade: "steel", Region: "Dortmund, DE", CrewSize: 20, Start: day(2027, time.February, 2), Requirements: []string{"a1", "insurance", "certificates"}, Languages: []string{"de", "en"}, CreatedAt: now.Add(-6 * time.Hour), UpdatedAt: now.Add(-30 * time.Minute)},
		{ID: "MM-2121", Title: "Klimatisierung Serverraum", Location: "Köln, DE", Category: "Heizung/Klima", Amount: "4 Anlagen", Budget: "EUR 74k", Status: "requested", Signal: "OK", Supplier: "Rhein Klima", Progress: 15, Attention: "Zugang nur nachts möglich", Trade: "hvac", Region: "Köln, DE", CrewSize: 4, Start: day(2026, time.October, 6), Requirements: []string{"a1", "insurance"}, Languages: []string{"de"}, CreatedAt: now.Add(-34 * time.Hour), UpdatedAt: now.Add(-8 * time.Hour)},
		{ID: "MM-2122", Title: "Büroausbau Bankfiliale", Location: "Genf, CH", Category: "Innenausbau", Amount: "640 m²", Budget: "EUR 190k", Status: "open", Signal: "OK", Supplier: "Léman Interiors", Progress: 0, Attention: "Sicherheitsfreigabe für Kolonne erforderlich", Trade: "interior", Region: "Genf, CH", CrewSize: 6, Start: day(2026, time.November, 23), Requirements: []string{"a1", "insurance"}, Languages: []string{"fr", "de"}, CreatedAt: now.Add(-26 * time.Hour), UpdatedAt: now.Add(-9 * time.Hour)},
		{ID: "MM-2123", Title: "Trockenbau Schulsanierung", Location: "Nürnberg, DE", Category: "Trockenbau", Amount: "3.400 m²", Budget: "EUR 148k", Status: "requested", Signal: "OK", Supplier: "Frankenbau", Progress: 20, Attention: "Arbeiten nur in den Ferien möglich", Trade: "drywall", Region: "Nürnberg, DE", CrewSize: 8, Start: day(2026, time.October, 26), Requirements: []string{"a1", "certificates"}, Languages: []string{"de", "pl"}, CreatedAt: now.Add(-50 * time.Hour), UpdatedAt: now.Add(-13 * time.Hour)},
		{ID: "MM-2124", Title: "Bäder- und Küchenausbau Neubauviertel", Location: "Rotterdam, NL", Category: "Sanitär", Amount: "210 Wohnungen", Budget: "EUR 480k", Status: "open", Signal: "OK", Supplier: "Nordline Build", Progress: 3, Attention: "Erste von drei Bauphasen", Trade: "sanitary", Region: "Rotterdam, NL", CrewSize: 7, Start: day(2027, time.January, 19), Requirements: []string{"a1", "insurance"}, Languages: []string{"nl", "en"}, CreatedAt: now.Add(-9 * time.Hour), UpdatedAt: now.Add(-time.Hour)},
		{ID: "MM-2125", Title: "Elektro Sanierung Altbauquartier", Location: "Dresden, DE", Category: "Elektro", Amount: "48 Wohnungen", Budget: "EUR 210k", Status: "process", Signal: "Review", Supplier: "Elbstrom", Progress: 72, Attention: "Denkmalschutz-Auflagen bei Leitungsführung", Trade: "electrical", Region: "Dresden, DE", CrewSize: 5, Start: day(2026, time.July, 14), Requirements: []string{"a1", "insurance"}, Languages: []string{"de"}, CreatedAt: now.Add(-310 * time.Hour), UpdatedAt: now.Add(-22 * time.Hour)},
	}
}

// Crews is the supply side of the demo market.
func Crews() []model.Crew {
	return []model.Crew{
		{ID: "CR-01", Name: "Kolonne Nowak", Company: "Nowak Montage Sp. z o.o.", Trades: []string{"electrical", "drywall"}, Regions: []string{"München, DE", "Stuttgart, DE", "DACH"}, Size: 8, Languages: []string{"pl", "de"}, Documents: []string{"a1", "insurance"}, AvailableFrom: day(2026, time.October, 1), AvailableNote: "ab 1. Oktober, 6 Wochen am Stück", Rate: "46-54 EUR/h", Rating: 4.6, JobsDone: 23, Note: "Feste Kolonne seit vier Jahren, eigener Transporter und Werkzeug, Erfahrung mit Bürogebäuden."},
		{ID: "CR-02", Name: "Steel Crew Rotterdam", Company: "Van Dijk Staalbouw BV", Trades: []string{"steel"}, Regions: []string{"Rotterdam, NL", "NL", "Antwerpen, BE"}, Size: 12, Languages: []string{"nl", "en"}, Documents: []string{"a1", "insurance", "certificates"}, AvailableFrom: day(2026, time.November, 1), AvailableNote: "ab November, mindestens 8 Wochen", Rate: "52-60 EUR/h", Rating: 4.8, JobsDone: 41, Note: "Hallenbau und Stahltreppen, zertifizierte Schweißer nach EN 1090."},
		{ID: "CR-03", Name: "Sanitärteam Alpen", Company: "Berger Haustechnik GmbH", Trades: []string{"sanitary", "hvac"}, Regions: []string{"Wien, AT", "Linz, AT", "AT"}, Size: 5, Languages: []string{"de"}, Documents: []string{"a1", "certificates"}, AvailableFrom: day(2026, time.September, 15), AvailableNote: "kurzfristig verfügbar, auch Wochenende", Rate: "48-58 EUR/h", Rating: 4.4, JobsDone: 17, Note: "Hotel- und Klinikbäder, Erfahrung mit laufendem Betrieb."},
		{ID: "CR-04", Name: "Elektro Kolonne Süd", Company: "Kraft Elektrotechnik", Trades: []string{"electrical", "energy"}, Regions: []string{"München, DE", "Augsburg, DE"}, Size: 6, Languages: []string{"de", "tr"}, Documents: []string{"a1", "insurance", "certificates", "tax"}, AvailableFrom: day(2026, time.October, 6), AvailableNote: "ab Oktober frei", Rate: "50-58 EUR/h", Rating: 4.7, JobsDone: 31, Note: "Photovoltaik und Gebäudeinstallation, eigene Hubarbeitsbühne."},
		{ID: "CR-05", Name: "Trockenbau Team Ost", Company: "Kowalski Ausbau", Trades: []string{"drywall", "interior"}, Regions: []string{"Berlin, DE", "Stuttgart, DE", "DE"}, Size: 10, Languages: []string{"pl", "de"}, Documents: []string{"a1"}, AvailableFrom: day(2026, time.September, 22), AvailableNote: "ab Ende September, 10 Wochen", Rate: "42-48 EUR/h", Rating: 4.1, JobsDone: 12, Note: "Großflächen und Brandschutzwände, Nachweise in Arbeit."},
		{ID: "CR-06", Name: "Klima Crew Rhein", Company: "Rheinluft Service", Trades: []string{"hvac"}, Regions: []string{"Frankfurt, DE", "Köln, DE"}, Size: 9, Languages: []string{"de", "en"}, Documents: []string{"a1", "insurance", "certificates"}, AvailableFrom: day(2026, time.November, 10), AvailableNote: "ab Mitte November", Rate: "55-65 EUR/h", Rating: 4.9, JobsDone: 28, Note: "Rechenzentren und Reinräume, Sicherheitsüberprüfung vorhanden."},

		// Same awkward-case rationale as the extra offers above: CR-07 carries
		// a paper that is about to expire, CR-08 speaks only Polish.
		{ID: "CR-07", Name: "Elektro Team West", Company: "Ruhrstrom Montage GmbH", Trades: []string{"electrical"}, Regions: []string{"Köln, DE", "Dortmund, DE"}, Size: 6, Languages: []string{"de"}, Documents: []string{"a1"}, AvailableFrom: day(2026, time.October, 1), AvailableNote: "sofort verfügbar", Rate: "47-53 EUR/h", Rating: 4.3, JobsDone: 19, Note: "A1-Bescheinigung läuft in 9 Tagen ab, Verlängerung ist beantragt aber noch nicht bestätigt."},
		{ID: "CR-08", Name: "Fliesenteam Krakau", Company: "Malinowski Wykończenia", Trades: []string{"interior"}, Regions: []string{"DE"}, Size: 5, Languages: []string{"pl"}, Documents: []string{"a1"}, AvailableFrom: day(2026, time.October, 15), AvailableNote: "reist für Aufträge in ganz Deutschland an", Rate: "38-44 EUR/h", Rating: 4.2, JobsDone: 9, Note: "Spricht ausschließlich Polnisch, Absprachen bisher über Bauleiter mit Sprachmittler."},
		{ID: "CR-09", Name: "Heizungsbau Team Nord", Company: "Nordklima Service", Trades: []string{"hvac"}, Regions: []string{"Hannover, DE", "Bremen, DE"}, Size: 7, Languages: []string{"de", "en"}, Documents: []string{"a1", "insurance"}, AvailableFrom: day(2026, time.November, 20), AvailableNote: "ab Ende November", Rate: "50-58 EUR/h", Rating: 4.5, JobsDone: 14, Note: "Lüftungs- und Klimasanierung im Bestand, arbeitet auch in bewohnten Gebäuden."},
		{ID: "CR-10", Name: "Stahlbau Team Basel", Company: "Rhybau AG", Trades: []string{"steel"}, Regions: []string{"Basel, CH", "Genf, CH"}, Size: 10, Languages: []string{"de", "fr"}, Documents: []string{"a1", "insurance", "certificates"}, AvailableFrom: day(2026, time.October, 19), AvailableNote: "ab 19. Oktober, 10 Wochen", Rate: "58-66 EUR/h", Rating: 4.8, JobsDone: 22, Note: "Messehallen und Industriebau, zertifizierte Schweißer nach EN 1090."},
		{ID: "CR-11", Name: "Sanitair Team Utrecht", Company: "De Vries Installatie BV", Trades: []string{"sanitary"}, Regions: []string{"Utrecht, NL", "Amsterdam, NL", "Rotterdam, NL"}, Size: 7, Languages: []string{"nl", "en"}, Documents: []string{"a1", "insurance"}, AvailableFrom: day(2027, time.January, 5), AvailableNote: "ab Januar, mehrphasig einsetzbar", Rate: "49-57 EUR/h", Rating: 4.6, JobsDone: 26, Note: "Neubauviertel und Sanierung, eigene Rohrleger und Klempner."},
		{ID: "CR-12", Name: "Energie Team Alpin", Company: "Alpin Energie GmbH", Trades: []string{"energy"}, Regions: []string{"Salzburg, AT", "Graz, AT", "AT"}, Size: 5, Languages: []string{"de"}, Documents: []string{"a1", "certificates"}, AvailableFrom: day(2026, time.September, 1), AvailableNote: "laufend verfügbar", Rate: "51-59 EUR/h", Rating: 4.7, JobsDone: 20, Note: "Wärmepumpen und PV-Umrüstung im Bestand, auch im laufenden Hotelbetrieb."},
	}
}
