// Package store persists everything the app knows: offers, conversations,
// feedback and the generated backlog.
//
// This file is the CONTRACT. The concrete SQLite implementation lives in
// sqlite.go; nothing outside this package may depend on that type.
package store

import (
	"context"
	"errors"

	"mm-machine/internal/model"
)

// ErrNotFound is returned by every lookup that finds nothing.
var ErrNotFound = errors.New("store: not found")

// OfferFilter narrows a pipeline query. Zero value means "everything".
//
// The first three fields serve the pipeline UI; the facet fields serve search,
// which turns a parsed Intent into one of these. Facets are OR within a field
// and AND across fields.
type OfferFilter struct {
	Status string // "" or "all" means any
	Query  string // free text over title, location, category, supplier
	Limit  int    // 0 means no limit

	Statuses     []string
	Trades       []string
	Regions      []string
	Requirements []string
	MinCrewSize  int
}

// FeedbackFilter narrows a feedback query.
type FeedbackFilter struct {
	Status string
	Kind   string
	Since  int64 // unix seconds; 0 means no bound
	Limit  int
}

// CrewFilter narrows a crew query, with the same OR-within/AND-across facet
// semantics as OfferFilter.
type CrewFilter struct {
	Query     string
	Trades    []string
	Regions   []string
	Documents []string
	MinSize   int
	Limit     int
}

// TextQuery is a full-text search across the corpus. Kinds may contain
// "offer" and/or "crew"; empty means both.
type TextQuery struct {
	Text  string
	Kinds []string
	Limit int
}

// TextHit is one full-text result. Score is higher-is-better and comparable
// only within one query.
type TextHit struct {
	Kind    string // offer | crew
	ID      string
	Score   float64
	Snippet string
}

// Store is the persistence port used by every handler package.
type Store interface {
	// Offers
	ListOffers(ctx context.Context, f OfferFilter) ([]model.Offer, error)
	GetOffer(ctx context.Context, id string) (model.Offer, error)
	CreateOffer(ctx context.Context, o model.Offer) (model.Offer, error)
	UpdateOffer(ctx context.Context, o model.Offer) (model.Offer, error)
	CountOffersByStatus(ctx context.Context) (map[string]int, error)

	// Static-ish content, seeded once and editable later.
	ListPerspectives(ctx context.Context) ([]model.Perspective, error)
	ListModules(ctx context.Context) ([]model.Module, error)
	ListRoadmap(ctx context.Context) ([]model.RoadmapItem, error)

	// Conversations and chat
	CreateConversation(ctx context.Context, c model.Conversation) (model.Conversation, error)
	GetConversation(ctx context.Context, id string) (model.Conversation, error)
	AppendMessage(ctx context.Context, m model.ChatMessage) (model.ChatMessage, error)
	ListMessages(ctx context.Context, conversationID string) ([]model.ChatMessage, error)

	// Feedback
	CreateFeedback(ctx context.Context, f model.Feedback) (model.Feedback, error)
	ListFeedback(ctx context.Context, f FeedbackFilter) ([]model.Feedback, error)
	SetFeedbackStatus(ctx context.Context, id int64, status string) error

	// Backlog (regenerated by the dev loop, so replace-all is the write path)
	ReplaceBacklog(ctx context.Context, items []model.BacklogItem) error
	ListBacklog(ctx context.Context) ([]model.BacklogItem, error)
	SetBacklogStatus(ctx context.Context, id int64, status string) error

	// Crews — the supply side: deployable teams.
	ListCrews(ctx context.Context, f CrewFilter) ([]model.Crew, error)
	GetCrew(ctx context.Context, id string) (model.Crew, error)
	UpsertCrew(ctx context.Context, c model.Crew) (model.Crew, error)

	// TextSearch is the full-text index over offers and crews. Implementations
	// must degrade to a substring scan rather than failing.
	TextSearch(ctx context.Context, q TextQuery) ([]TextHit, error)

	// Profiles — who the visitor is, learned during onboarding.
	UpsertProfile(ctx context.Context, p model.Profile) (model.Profile, error)
	GetProfile(ctx context.Context, id string) (model.Profile, error)

	// Saved searches
	SaveSearch(ctx context.Context, s model.SavedSearch) (model.SavedSearch, error)
	ListSavedSearches(ctx context.Context, profileID string) ([]model.SavedSearch, error)

	Close() error
}
