// Package store persists everything the app knows: offers, conversations,
// feedback and the generated backlog.
//
// This file is the CONTRACT. The concrete SQLite implementation lives in
// sqlite.go; nothing outside this package may depend on that type.
package store

import (
	"context"
	"errors"

	"mm-machine/internal/model"
)

// ErrNotFound is returned by every lookup that finds nothing.
var ErrNotFound = errors.New("store: not found")

// OfferFilter narrows a pipeline query. Zero value means "everything".
type OfferFilter struct {
	Status string // "" or "all" means any
	Query  string // free text over title, location, category, supplier
	Limit  int    // 0 means no limit
}

// FeedbackFilter narrows a feedback query.
type FeedbackFilter struct {
	Status string
	Kind   string
	Since  int64 // unix seconds; 0 means no bound
	Limit  int
}

// Store is the persistence port used by every handler package.
type Store interface {
	// Offers
	ListOffers(ctx context.Context, f OfferFilter) ([]model.Offer, error)
	GetOffer(ctx context.Context, id string) (model.Offer, error)
	CreateOffer(ctx context.Context, o model.Offer) (model.Offer, error)
	UpdateOffer(ctx context.Context, o model.Offer) (model.Offer, error)
	CountOffersByStatus(ctx context.Context) (map[string]int, error)

	// Static-ish content, seeded once and editable later.
	ListPerspectives(ctx context.Context) ([]model.Perspective, error)
	ListModules(ctx context.Context) ([]model.Module, error)
	ListRoadmap(ctx context.Context) ([]model.RoadmapItem, error)

	// Conversations and chat
	CreateConversation(ctx context.Context, c model.Conversation) (model.Conversation, error)
	GetConversation(ctx context.Context, id string) (model.Conversation, error)
	AppendMessage(ctx context.Context, m model.ChatMessage) (model.ChatMessage, error)
	ListMessages(ctx context.Context, conversationID string) ([]model.ChatMessage, error)

	// Feedback
	CreateFeedback(ctx context.Context, f model.Feedback) (model.Feedback, error)
	ListFeedback(ctx context.Context, f FeedbackFilter) ([]model.Feedback, error)
	SetFeedbackStatus(ctx context.Context, id int64, status string) error

	// Backlog (regenerated by the dev loop, so replace-all is the write path)
	ReplaceBacklog(ctx context.Context, items []model.BacklogItem) error
	ListBacklog(ctx context.Context) ([]model.BacklogItem, error)
	SetBacklogStatus(ctx context.Context, id int64, status string) error

	Close() error
}
